- name: Create Girder hpccloud user
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    user:
      firstName: "hpccloud"
      lastName: "hpccloud"
      login: "hpccloud"
      password: "{{ hpccloud_password }}"
      email: "hpccloud@kitware.com"
      admin: yes
    state: present

- name: Create Girder cumulus user
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "hpccloud"
    password: "{{ hpccloud_password }}"
    user:
      firstName: "cumulus"
      lastName: "cumulus"
      login: "cumulus"
      password: "{{ cumulus_password }}"
      email: "cumulus@kitware.com"
      admin: yes
    state: present

- name: Create Girder cumulus group
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "hpccloud"
    password: "{{ hpccloud_password }}"
    group:
      name: "cumulus"
      description: "The cumulus group"
      users:
        - login: cumulus
          type: member

- name: Create filesystem assetstore
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    apiRoot: "{{girder_api_root}}"
    username: "hpccloud"
    password: "{{ hpccloud_password }}"
    assetstore:
      name: "Filesystem Assetstore"
      type: "filesystem"
      root: "/assetstore"
      current: true
    state: present

- name: Enable CORS requests
  girder:
    host: "{{girder_host}}"
    port: "{{girder_port}}"
    scheme: "{{girder_scheme}}"
    username: "hpccloud"
    password: "{{ hpccloud_password }}"
    setting:
      key: "{{item.key}}"
      value: "{{item.value}}"
    state: present
  with_items:
    - {
      "key": "core.cors.allow_origin",
      "value": "*"
    }
    - {
      "key": "core.cors.allow_methods",
      "value": "GET"
    }
  when: enable_cors is defined

- include: dev.yml
  when: dev is defined
